fix

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -73,15 +73,15 @@ jobs:
             echo "Jacoco Test Report not found!" && exit 1
           fi
           
-          # Vérification du taux de couverture
-          - name: Check Coverage Threshold
-            run: |
-              COVERAGE=$(xmllint --xpath "string(//report/counter[@type='LINE']/@covered)" app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml)
-              TOTAL=$(xmllint --xpath "string(//report/counter[@type='LINE']/@missed)" app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml)
-              TOTAL=$(($COVERAGE + $TOTAL))
-              PERCENTAGE=$((COVERAGE * 100 / TOTAL))
-              echo "Coverage is $PERCENTAGE%"
-              if [ "$PERCENTAGE" -lt 90 ]; then
-                echo "Coverage threshold not met: $PERCENTAGE% (required: 90%)"
-                exit 1
-              fi
+      # Vérification du taux de couverture
+      - name: Check Coverage Threshold
+        run: |
+          COVERAGE=$(xmllint --xpath "string(//report/counter[@type='LINE']/@covered)" app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml)
+          TOTAL=$(xmllint --xpath "string(//report/counter[@type='LINE']/@missed)" app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml)
+          TOTAL=$(($COVERAGE + $TOTAL))
+          PERCENTAGE=$((COVERAGE * 100 / TOTAL))
+          echo "Coverage is $PERCENTAGE%"
+          if [ "$PERCENTAGE" -lt 90 ]; then
+            echo "Coverage threshold not met: $PERCENTAGE% (required: 90%)"
+            exit 1
+          fi
